In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import csv

df = pd.read_csv('csv/dataset_part1.csv')

print('\nDataFrame shape: ', df.shape)
print('\nDataFrame info: ', df.info())

#print('\nColumn headers:')
#for i, col in enumerate(df):
#    print(f'{i+1}, {col}')

print('\nFirst 10 rows: ', df.head(10))
print('\nLast 10 rows: ', df.tail(10))

df.columns.to_list()

DataFrame shape:  (264, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Paper               264 non-null    object
 1   Country             264 non-null    object
 2   Geothermal Field    264 non-null    object
 3   Well Name           264 non-null    object
 4   Sample ID           264 non-null    object
 5   Depth (m)           183 non-null    object
 6   Measured Temp (°C)  264 non-null    object
 7   pH                  214 non-null    object
 8   Na (mg/L)           264 non-null    object
 9   Ca (mg/L)           264 non-null    object
 10  K (mg/L)            263 non-null    object
 11  Mg (mg/L)           258 non-null    object
 12  Cl (mg/L)           264 non-null    object
 13  SiO₂ (mg/L)         232 non-null    object
dtypes: object(14)
memory usage: 29.0+ KB

DataFrame info:  None

First 10 rows:                     Paper  Country    Geothermal Field    Well Name  \
0  Pauwels et. al., 1993   France  Soultz-sous-Forêts         GPK1
1  Pauwels et. al., 1993   France  Soultz-sous-Forêts         GPK1
2  Pauwels et. al., 1993   France  Soultz-sous-Forêts         GPK1
3  Pauwels et. al., 1993   France  Soultz-sous-Forêts         GPK1
4  Pauwels et. al., 1993   France  Soultz-sous-Forêts         EPS1
5  Pauwels et. al., 1993   France  Soultz-sous-Forêts         4616
6  Pauwels et. al., 1993   France         Cronenbourg  Cronenbourg
7  Pauwels et. al., 1993  Germany                Bühl         Bühl
8  Pauwels et. al., 1993  Germany                Bühl         Bühl
9  Pauwels et. al., 1993  Germany            Bruchsal          GB1

     Sample ID Depth (m) Measured Temp (°C)    pH Na (mg/L) Ca (mg/L)  \
0        KS228      1820             137,00  5,82  28200,00   6730,00
1        KD005      1810             137,00  5,22  27200,00   6760,00
2        KD006      1845             137,00  5,02  28000,00   6960,00
3        KD007      1930             137,00  5,14  27900,00   6930,00
4         EPS1      2175             150,00   NaN  28300,00   7990,00
5         4616      1403             116,00  5,50  27800,00   8400,00
6  Cronenbourg      2870             140,00   NaN  31500,00   4810,00
7        B2460      2460             115,00   NaN  64000,00  11600,00
8        B2535      2535             115,00   NaN  63900,00  11700,00
9          GB1      1800             114,00   NaN  38100,00   7740,00

  K (mg/L) Mg (mg/L)  Cl (mg/L) SiO₂ (mg/L)
0  3320,00    150,00   58500,00       97,00
1  3210,00    145,00   57000,00       97,00
2  3280,00    152,00   58100,00       94,00
3  3400,00    152,00   58500,00       93,00
4  3360,00    122,00   59800,00      150,00
5  3450,00    140,00   60900,00      110,00
6  4030,00    126,00   62000,00      143,00
7   494,00   1930,00  120300,00         NaN
8   503,00   1900,00  120500,00         NaN
9  2200,00    434,00   75200,00       41,80

Last 10 rows:                         Paper      Country Geothermal Field Well Name  \
254  Mroczek et. al., (2003)  New Zealand          Rotorua       M25
255  Mroczek et. al., (2003)  New Zealand          Rotorua      1016
256          Giggenbach 1978        Chile         El Tatio        T1
257          Giggenbach 1978        Chile         El Tatio        T2
258          Giggenbach 1978        Chile         El Tatio        T3
259          Giggenbach 1978        Chile         El Tatio        T4
260          Giggenbach 1978        Chile         El Tatio        T5
261        Villarroel (2014)      Bolivia    Sol de Mañana     SM-01
262        Villarroel (2014)      Bolivia    Sol de Mañana     SM-02
263        Villarroel (2014)      Bolivia    Sol de Mañana     SM-03

    Sample ID Depth (m) Measured Temp (°C)        pH Na (mg/L) Ca (mg/L)  \
254       M25       245             211,00      7,58    950,00     16,70
255      1016       120             135,00      7,77    577,00     17,00
256        T1       750             211,00  45875,00   3340,00    127,00
257        T2       750             227,00  45875,00   3430,00    127,00
258        T3       750             253,00  45814,00   2570,00    107,00
259        T4       750             229,00  45844,00   3430,00    129,00
260        T5       750             212,00  45844,00   3760,00    150,00
261     SM-01      1180             249,00      6,98   4060,00    206,00
262     SM-02    1486,5             250,00      7,12   4080,00    192,00
263     SM-03      1406             247,00      4,32   4310,00    219,00

    K (mg/L) Mg (mg/L) Cl (mg/L) SiO₂ (mg/L)
254   125,00      0,02   1516,00      343,00
255    54,00      0,09    581,00      293,00
256   293,00       NaN   5820,00      290,00
257   298,00       NaN   6020,00      278,00
258   173,00       NaN   4490,00      244,00
259   246,00       NaN   5650,00      239,00
260   343,00       NaN   6690,00      258,00
261   704,00     42,00   7160,00      784,00
262   697,00     27,00   7100,00     1330,00
263   720,00    100,00   7500,00      619,00

['Paper',
 'Country',
 'Geothermal Field',
 'Well Name',
 'Sample ID',
 'Depth (m)',
 'Measured Temp (°C)',
 'pH',
 'Na (mg/L)',
 'Ca (mg/L)',
 'K (mg/L)',
 'Mg (mg/L)',
 'Cl (mg/L)',
 'SiO₂ (mg/L)']

In [2]:
### Rename a column name 

df1 = pd.read_csv("csv/dataset_GDR_raw.csv")

df1 = df1.rename(columns={'Na ': 'Na'})

output_path = 'csv/dataset_GDR_raw.csv'
df1.to_csv(output_path, index=False)

df1.columns.tolist()

['well_sample', 'temp_measured', 'pH', 'Na', 'K', 'Ca', 'Mg', 'Cl', 'SO4']

In [3]:
### Princial characteristics of dataset

print('\nColumn names:\n', df.columns.tolist())
print('\nData types:\n', df.dtypes)
print('\nMissing values:\n', df.isnull().sum())
print('\nNaN entries:\n', df.isna().sum())
print('\nDuplicates Count:', df.duplicated().sum())

print('\nSummary Statistics:\n', df.describe(include='all').T)

Column names:
 ['well_sample', 'temp_measured', 'pH', 'Na', 'K', 'Ca', 'Mg', 'Cl', 'SO4']

Data types:
 well_sample      object
temp_measured    object
pH               object
Na               object
K                object
Ca               object
Mg               object
Cl               object
SO4              object
dtype: object

Missing values:
 well_sample         3
temp_measured       0
pH                794
Na               1649
K                1683
Ca               1633
Mg               1690
Cl                666
SO4              1286
dtype: int64

NaN entries:
 well_sample         3
temp_measured       0
pH                794
Na               1649
K                1683
Ca               1633
Mg               1690
Cl                666
SO4              1286
dtype: int64

Duplicates Count: 45

Summary Statistics:
               count unique        top freq
well_sample    3178   1084  NWIS Site  192
temp_measured  3181    451       90,0  169
pH             2387     90        7,4  112
Na             1532    624      380,0   20
K              1498    330        4,0   27
Ca             1548    420       16,0   28
Mg             1491    285        0,0  132
Cl             2515   1418       20,0   24
SO4            1895    458      120,0   41

In [4]:
### Eliminate rows that are not wells

original_len = len(df)

# Create a pattern to match using regex
pattern = r'spring|fumarole|thermal spring'

df = df[~df['well_sample'].str.lower().str.contains(pattern, na=False)]

print(f'Original number of rows: {original_len}')
print(f'Number of rows after filtering: {len(df)}')
print(f'Number of rows removed: {original_len - len(df)}')

print('\nFirst 10 rows of cleaned dataset:')
display(df.head(10))

Original number of rows: 3181
Number of rows after filtering: 2004
Number of rows removed: 1177

First 10 rows of cleaned dataset:

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
0,California State 2-14 well,"351,0","5,7","43700,0","13700,0","24000,0","29,0","120800,0","220,0"
1,California State 2-14 well,"351,0","5,3","50200,0","16700,0","26200,0","14,0","142600,0","3,4"
2,California State 2-14 well,"351,0","5,7","43200,0","14000,0","21600,0","35,0","176,0","275,0"
3,IID 2,"349,0","5,4","64700,0","21700,0","32600,0","100,0","189000,0",NaN
4,RIVER RANCH 1 - MAGMA POWER CO.,"345,0","4,0","74700,0","21900,0","39700,0","59,0","216000,0",NaN
5,RIVER RANCH 1 - MAGMA POWER CO.,"345,0","5,2","7400,0","23600,0","41000,0","62,0","225000,0","35,0"
6,"IID 2 - IMPERIAL THERMAL PRODUCTS, INC.","330,0","4,6","53000,0","16500,0","27800,0","10,0","155000,0",NaN
7,MAGMAMAX 3 - MAGMA POWER CO.,"321,0",NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"IID 1 - IMPERIAL THERMAL PRODUCTS, INC.","316,0",NaN,"51000,0","20000,0","33000,0","37,0","182300,0",NaN
9,"IID 1 - IMPERIAL THERMAL PRODUCTS, INC.","316,0",NaN,NaN,NaN,NaN,"33,0",NaN,NaN

In [5]:
### Keep only rows that contain "well" or "Well"

original_len = len(df)

# Create a pattern to match "well"
pattern = r'well'

df = df[df['well_sample'].str.lower().str.contains(pattern, na=False)]

print(f'Original number of rows: {original_len}')
print(f'Number of rows after filtering: {len(df)}')
print(f'Number of rows removed: {original_len - len(df)}')

print('\nFirst 10 rows of cleaned dataset:')
display(df.head(10))

Original number of rows: 2004
Number of rows after filtering: 701
Number of rows removed: 1303

First 10 rows of cleaned dataset:

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
0,California State 2-14 well,"351,0","5,7","43700,0","13700,0","24000,0","29,0","120800,0","220,0"
1,California State 2-14 well,"351,0","5,3","50200,0","16700,0","26200,0","14,0","142600,0","3,4"
2,California State 2-14 well,"351,0","5,7","43200,0","14000,0","21600,0","35,0","176,0","275,0"
26,NWIS Well 026S040E22P001M,"300,0","8,6","410,0","4,9","1,8","0,5","11,0","12,0"
27,NWIS Well 026S040E22P001M,"300,0","8,7","17,0","6,0","55,0","15,0","68,0","47,0"
28,California State 2-14 well,"298,0","2,4","47400,0","14400,0","27240,0","36,0","132200,0","1,0"
29,California State 2-14 well,"298,0","4,3","43400,0","16900,0","28790,0","19,0","135500,0",NaN
48,California State 2-14 well,"250,0","2,5","54600,0","21300,0","39050,0","52,0","174800,0","1,2"
52,California State 2-14 well,"244,0","8,2","2,0","1,0","3,0","1,0","1,0","19,6"
53,California State 2-14 well,"244,0","5,7","60500,0","18800,0","31100,0","38,0","164900,0","6,0"

In [6]:
### Change commas for dots

numeric_cols = df.select_dtypes(include=['object']).columns

for col in numeric_cols:
    df[col] = df[col].astype(str).str.replace(',', '.')
   
    try:
        df[col] = pd.to_numeric(df[col])
    except:
        pass  # Keep as string if conversion fails
    
print("\nFirst 10 rows after replacing commas with dots:")
display(df.head(10))

print("\nUpdated data types:")
print(df.dtypes)

First 10 rows after replacing commas with dots:

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
0,California State 2-14 well,351.0,5.7,43700.0,13700.0,24000.0,29.0,120800.0,220.0
1,California State 2-14 well,351.0,5.3,50200.0,16700.0,26200.0,14.0,142600.0,3.4
2,California State 2-14 well,351.0,5.7,43200.0,14000.0,21600.0,35.0,176.0,275.0
26,NWIS Well 026S040E22P001M,300.0,8.6,410.0,4.9,1.8,0.5,11.0,12.0
27,NWIS Well 026S040E22P001M,300.0,8.7,17.0,6.0,55.0,15.0,68.0,47.0
28,California State 2-14 well,298.0,2.4,47400.0,14400.0,27240.0,36.0,132200.0,1.0
29,California State 2-14 well,298.0,4.3,43400.0,16900.0,28790.0,19.0,135500.0,nan
48,California State 2-14 well,250.0,2.5,54600.0,21300.0,39050.0,52.0,174800.0,1.2
52,California State 2-14 well,244.0,8.2,2.0,1.0,3.0,1.0,1.0,19.6
53,California State 2-14 well,244.0,5.7,60500.0,18800.0,31100.0,38.0,164900.0,6.0

Updated data types:
well_sample       object
temp_measured    float64
pH                object
Na                object
K                 object
Ca                object
Mg                object
Cl                object
SO4               object
dtype: object

In [7]:
### Check for NaN and missing values. Eliminate rows with more than 0 NaN

columns_to_check = ['pH', 'Na', 'K', 'Ca', 'Mg', 'Cl', 'SO4']

# First, replace string 'nan' with numpy.nan
df[columns_to_check] = df[columns_to_check].replace('nan', np.nan) # 'nan' not a number in Pandas. Numpy takes both.
df[columns_to_check] = df[columns_to_check].replace('NaN', np.nan) # 'NaN' not a number in Python.

# Count missing values
nan_counts = df[columns_to_check].isna().sum()
print("Missing value counts in each column:")
print(nan_counts)

# Print unique values to check for other potential missing value representations
for col in columns_to_check:
    print(f"\nUnique values in {col}:")
    print(df[col].unique())

# Count how many missing values each row has
row_nan_counts = df[columns_to_check].isna().sum(axis=1)

# Print total rows before filtering
print(f"\nTotal rows before filtering: {len(df)}")

# Keep only rows with 1 or fewer NaN values in the specified columns
df_cleaned = df[row_nan_counts <= 1]

print(f"Total rows after filtering: {len(df_cleaned)}")
print(f"Rows removed: {len(df) - len(df_cleaned)}")

df = df_cleaned

print("\nFirst few rows of cleaned dataset:")
display(df.head(10))
display(df.tail(10))

Missing value counts in each column:
pH     126
Na     347
K      354
Ca     338
Mg     348
Cl     132
SO4    307
dtype: int64

Unique values in pH:
['5.7' '5.3' '8.6' '8.7' '2.4' '4.3' '2.5' '8.2' '5.8' '2.0' '8.9' '6.9'
 '6.6' nan '6.4' '7.6' '7.8' '7.9' '7.3' '7.7' '10.0' '9.3' '5.9' '8.8'
 '9.0' '7.1' '6.1' '8.3' '6.5' '6.2' '6.3' '7.0' '5.4' '3.5' '6.0' '4.6'
 '7.4' '6.8' '9.2' '5.6' '7.2' '6.7' '9.8' '4.8' '7.5' '8.4' '10.4' '8.0'
 '10.8' '10.2' '10.7' '8.5' '3.8' '10.5' '8.1' '4.5' '4.9' '11.2' '11.0'
 '11.4' '9.6' '11.6' '9.1' '11.5' '10.6' '11.8' '9.5' '9.9' '9.4' '9.7']

Unique values in Na:
['43700.0' '50200.0' '43200.0' '410.0' '17.0' '47400.0' '43400.0'
 '54600.0' '2.0' '60500.0' '58200.0' '60800.0' '54100.0' nan '1100.0'
 '60000.0' '4980.0' '57900.0' '8.1' '607.0' '86.5' '66.0' '45.0' '660.0'
 '232.0' '2000.0' '56.0' '53.2' '48.0' '499.7' '0.9' '350.0' '370.0'
 '620.0' '594.0' '673.0' '653.0' '340.0' '360.0' '627.0' '330.0' '593.0'
 '665.0' '28.0' '8.4' '610.0' '223.0' '600.0' '1420.0' '385.0' '168.0'
 '0.2' '741.0' '691.0' '611.0' '624.0' '49.0' '197.0' '70.0' '446.5'
 '692.0' '320.0' '604.0' '636.0' '628.0' '613.0' '641.0' '792.0' '570.0'
 '407.0' '95.5' '1.0' '644.0' '429.0' '250.0' '806.0' '180.0' '450.0'
 '615.0' '643.0' '150.0' '295.0' '675.0' '52.0' '672.0' '347.0' '276.0'
 '1200.0' '40.0' '110000.0' '654.0' '631.0' '633.0' '626.0' '646.0'
 '605.0' '980.0' '637.0' '635.0' '1900.0' '14.0' '22.0' '135.0' '19.0'
 '612.0' '630.0' '2230.0' '29.0' '322.0' '670.0' '560.0' '590.0' '639.0'
 '655.0' '608.0' '343.0' '5.4' '4.2' '688.0' '2200.0' '200.0' '6.1' '15.0'
 '57.0' '72.0' '68.0' '586.0' '569.0' '657.0' '8.2' '614.0' '625.0'
 '686.0' '390.0' '547.0' '623.0' '143.0' '640.0' '694.0' '4700.0' '0.3'
 '840.0' '1298.0' '1400.0' '7.6' '214.0' '230.0' '39.0' '584.0' '690.0'
 '493.0' '596.0' '46.0' '81.0' '43.0' '1760.0' '1050.0' '1350.0' '12.0'
 '245.0' '3.5' '67.0' '62.0' '1680.0' '13.0' '50.0' '186.0' '100000.0'
 '364.0' '5.5' '35.0' '9.1' '497.0' '470.0' '506.0' '71000.0' '70700.0'
 '108.0' '42.0' '499.0' '63000.0' '332.0' '263.0' '1000.0' '74600.0'
 '185.0' '55.0' '260.0' '5470.0' '324.0' '298.0' '24.0' '193.0' '44.0'
 '280.0' '297.0' '720.0' '335.0' '270.0' '29.4' '38.4' '650.0' '703.0'
 '210.0' '127.0' '386.0' '1500.0' '1480.0' '18.7' '541.0' '510.0' '2.8'
 '53.0' '77.0' '667.0' '728.0' '192.0' '22.2' '20.0' '763.0' '195.0'
 '110.0' '21.0' '736.0' '405.0' '461.0' '467.0' '65.0' '56.9' '530.0'
 '400.0' '65500.0' '120.0' '99.0' '1550.0' '75.0' '203.0' '64500.0'
 '1600.0' '63.0' '550.0' '243.0']

Unique values in K:
['13700.0' '16700.0' '14000.0' '4.9' '6.0' '14400.0' '16900.0' '21300.0'
 '1.0' '18800.0' '18500.0' '19300.0' '16500.0' nan '430.0' '18200.0'
 '1460.0' '2.5' '52.0' '3.4' '7.6' '65.0' '22.0' '232.0' '3.3' '4.4'
 '10.0' '74.2' '0.3' '36.0' '40.0' '51.0' '79.0' '90.0' '48.0' '31.0'
 '56.0' '33.0' '32.0' '78.0' '87.0' '6.3' '4.0' '77.0' '30.0' '11.7'
 '133.0' '0.1' '91.0' '59.0' '61.0' '0.2' '0.4' '18.0' '28.0' '4.2' '67.8'
 '86.3' '34.0' '75.0' '86.0' '54.0' '60.0' '53.0' '49.0' '19.0' '64.0'
 '13.1' '1.3' '55.0' '66.7' '8.2' '24.0' '72.0' '17.0' '27.0' '5.7'
 '7000.0' '23.0' '50.0' '4.6' '22.6' '3.0' '249.0' '7.3' '5.2' '16.0'
 '80.0' '70.0' '74.0' '0.5' '2.3' '255.0' '57.0' '2.4' '1.8' '4.7' '6.1'
 '7.4' '69.0' '62.1' '62.0' '2.2' '41.0' '5.8' '11.8' '46.0' '300.0'
 '88.0' '110.0' '120.0' '4.3' '9.0' '38.0' '58.0' '5.0' '7.2' '8.4'
 '154.0' '29.0' '240.0' '15.0' '0.8' '6.8' '5.5' '8.8' '5.6' '3.8' '1.6'
 '2100.0' '7.9' '2.9' '74.6' '6380.0' '5950.0' '76.8' '3800.0' '13.8'
 '31.2' '5000.0' '8.9' '1.4' '7.7' '44.0' '14.0' '67.6' '109.0' '21.0'
 '12.0' '3.2' '9.4' '10.6' '6.9' '39.0' '42.0' '20.0' '0.6' '63.0' '66.0'
 '9.1' '0.7' '1.1' '1.2' '13.0' '8.7' '73.0' '1.7' '26.0' '8.0' '1250.0'
 '1800.0' '35.0']

Unique values in Ca:
['24000.0' '26200.0' '21600.0' '1.8' '55.0' '27240.0' '28790.0' '39050.0'
 '3.0' '31100.0' '29900.0' '27200.0' nan '686.0' '33910.0' '1140.0'
 '33860.0' '2.1' '31.0' '21.0' '117.0' '123.0' '62.0' '3.6' '109.0' '12.0'
 '86.0' '160.0' '8.4' '0.1' '6.9' '1.6' '16.6' '3.4' '15.0' '3.9' '4.2'
 '14.5' '5.3' '2.5' '4.7' '8.2' '9.2' '14.0' '49.0' '2.3' '48.0' '6.7'
 '5.7' '70.4' '1.4' '70.0' '4.4' '0.4' '6.0' '2.7' '5.8' '16.3' '13.8'
 '2.8' '2.2' '18.0' '25.0' '7.5' '2.6' '2.9' '13.7' '15.8' '13.2' '14.4'
 '15.7' '38.0' '4.6' '8.0' '5.6' '0.2' '14.9' '7.2' '45.0' '13.0' '4.9'
 '13.9' '17.5' '98.0' '73.0' '224.0' '43.0' '33.0' '5.0' '58.0' '83.0'
 '1300.0' '5.9' '15.9' '18.3' '15.2' '15.3' '14.8' '16.0' '7.4' '18.5'
 '68.0' '590.0' '5.1' '69.0' '28.1' '51.0' '15.4' '110.0' '14.6' '23.0'
 '87.0' '78.0' '65.0' '7.9' '244.0' '3.3' '3.2' '3.7' '20.6' '19.9' '70.3'
 '0.8' '81.0' '1.9' '42.4' '64.0' '4.0' '46.0' '7.8' '0.3' '4.8' '15.5'
 '5.4' '5.5' '22.2' '19.0' '19.3' '21.6' '11.0' '10.0' '20.0' '380.0'
 '24.0' '140.0' '148.0' '2.0' '1.0' '1.7' '56.0' '80.0' '8.3' '245.0'
 '120.0' '67.1' '150.0' '7.1' '42.0' '142.0' '104.0' '27.0' '7.0' '22.0'
 '26.0' '8.7' '9.6' '45000.0' '46900.0' '78.2' '9.0' '72.0' '1700.0'
 '82.0' '44200.0' '17.0' '32.0' '84.0' '52.0' '273.0' '4.5' '14.7' '60.0'
 '126.0' '103.0' '460.0' '7.7' '108.0' '95.8' '510.0' '53.0' '81.4' '59.8'
 '66.0' '39.0' '40.0' '96.0' '71.5' '54.0' '28.0' '32600.0' '47.0' '1.1'
 '530.0' '29.0' '35.0' '130.0']

Unique values in Mg:
['29.0' '14.0' '35.0' '0.5' '15.0' '36.0' '19.0' '52.0' '1.0' '38.0'
 '41.0' '1010.0' nan '3.0' '0.1' '12.0' '24.0' '30.4' '22.0' '21.0' '0.4'
 '3.2' '31.0' '42.0' '< .01' '0.2' '0.0' '0.6' '2.8' '17.0' '4.9' '33.0'
 '< .07' '2.2' '< .02' '0.3' '0.8' '5.3' '18.0' '27.0' '4.5' '1.2' '26.0'
 '23.0' '2.0' '41.2' '5.2' '7.7' '6.0' '4.6' '30.0' '3000.0' '760.0'
 '20.0' '10.0' '7.2' '126.0' '20.3' '10.2' '28.0' '2.3' '13.0' '16.0'
 '7.4' '86.0' '9.5' '57.0' '7.0' '11.0' '9.0' 'N' '4.0' '2.5' '18.8' '5.4'
 '6.4' '130.0' '2300.0' '40.0' '60.1' '8.2' '3840.0' '1860.0' '65.1'
 '39.0' '2400.0' '< .002' '2.1' '3490.0' '0.7' '32.0' '1.3' '25.0' '84.0'
 '89.0' '4.1' '85.0' '57.7' '180.0' '1.7' '13.7' '190.0' '1.6' '1.4'
 '19.2' '13.3' '1.9' '1.5' '4.4' '29.9' '3700.0' '< .05' '0.05' '50.0'
 '4030.0']

Unique values in Cl:
['120800.0' '142600.0' '176.0' '11.0' '68.0' '132200.0' '135500.0'
 '174800.0' '1.0' '164900.0' '167208.0' '161100.0' '153000.0' nan '3630.0'
 '165300.0' '12500.0' '169600.0' '22.0' '3.5' '16.0' '23.0' '19.0' '92.0'
 '116.0' '83.0' '4.0' '874.0' '46.0' '3400.0' '28.0' '20.0' '37.0' '250.0'
 '416.0' '45.0' '44.0' '43.0' '794.0' '50.0' '51.0' '48.0' '52.0' '53.0'
 '54.0' '6.0' '67.0' '63.0' '64.0' '72.0' '73.0' '69.0' '71.0' '65.0'
 '66.0' '70.0' '15.0' '5.1' '230.0' '810.0' '889.0' '85.0' '82.0' '87.0'
 '436.0' '89.0' '84.0' '2340.0' '86.0' '305.0' '91.0' '93.0' '922.0'
 '105.0' '104.0' '100.0' '102.0' '107.0' '99.0' '101.0' '103.0' '106.0'
 '110.0' '5.4' '61.0' '7.6' '122.0' '119.0' '118.0' '115.0' '130.0'
 '114.0' '125.0' '124.0' '126.0' '120.0' '121.0' '117.0' '135.0' '132.0'
 '134.0' '131.0' '133.0' '860.0' '24.0' '235.0' '137.0' '141.0' '144.0'
 '140.0' '139.0' '148.0' '155.0' '350.0' '153.0' '154.0' '160.0' '29.0'
 '996.0' '383.0' '165.0' '166.0' '171.0' '170.0' '169.0' '164.0' '167.0'
 '168.0' '177.0' '490.0' '554.0' '21.0' '56.0' '878.0' '244.0' '36.0'
 '2000.0' '95.0' '190000.0' '187.0' '181.0' '180.0' '178.0' '183.0'
 '185.0' '194.0' '182.0' '193.0' '190.0' '179.0' '184.0' '197.0' '198.0'
 '600.0' '801.0' '200.0' '207.0' '208.0' '202.0' '201.0' '205.0' '206.0'
 '658.0' '1000.0' '209.0' '211.0' '9.7' '57.0' '13.0' '7.5' '218.0'
 '220.0' '10.0' '212.0' '217.0' '222.0' '3740.0' '225.0' '223.0' '224.0'
 '31.0' '55.0' '229.0' '345.0' '231.0' '232.0' '233.0' '779.0' '510.0'
 '239.0' '243.0' '248.0' '247.0' '246.0' '245.0' '11.2' '253.0' '261.0'
 '254.0' '3600.0' '257.0' '256.0' '255.0' '258.0' '259.0' '17.2' '30.0'
 '486.0' '262.0' '263.0' '7.3' '266.0' '270.0' '267.0' '269.0' '268.0'
 '271.0' '0.7' '279.0' '285.0' '288.0' '284.0' '287.0' '40.0' '300.0'
 '299.0' '298.0' '294.0' '295.0' '297.0' '308.0' '309.0' '313.0' '316.0'
 '317.0' '319.0' '320.0' '321.0' '322.0' '326.0' '327.0' '328.0' '330.0'
 '332.0' '902.0' '333.0' '336.0' '337.0' '9100.0' '340.0' '341.0' '342.0'
 '347.0' '356.0' '357.0' '358.0' '360.0' '361.0' '362.0' '363.0' '365.0'
 '366.0' '371.0' '32.0' '2225.0' '378.0' '2320.0' '377.0' '379.0' '386.0'
 '387.0' '390.0' '391.0' '397.0' '395.0' '3.1' '42.0' '406.0' '407.0'
 '408.0' '553.0' '421.0' '426.0' '427.0' '431.0' '457.0' '473.0' '491.0'
 '492.0' '497.0' '499.0' '508.0' '512.0' '533.0' '2790.0' '1830.0' '539.0'
 '537.0' '538.0' '540.0' '2250.0' '3.0' '5.0' '195.0' '547.0' '548.0'
 '6.4' '41.0' '790.0' '937.0' '579.0' '578.0' '567.0' '8.4' '47.0' '830.0'
 '170000.0' '2.0' '844.0' '617.0' '0.6' '621.0' '622.0' '623.0' '372.0'
 '614.0' '629.0' '60.0' '12.0' '631.0' '6.9' '642.0' '650.0' '649.0'
 '651.0' '652.0' '211000.0' '219600.0' '662.0' '659.0' '660.0' '664.0'
 '663.0' '674.0' '672.0' '667.0' '676.0' '677.0' '678.0' '687.0' '689.0'
 '683.0' '110000.0' '693.0' '690.0' '14.0' '705.0' '707.0' '1500.0'
 '695.0' '210900.0' '172.0' '702.0' '694.0' '714.0' '8480.0' '215.0'
 '718.0' '715.0' '719.0' '734.0' '720.0' '736.0' '1100.0' '768.0' '767.0'
 '746.0' '760.0' '752.0' '757.0' '743.0' '21.1' '43.3' '1400.0' '870.0'
 '824.0' '770.0' '775.0' '17.0' '780.0' '798.0' '792.0' '793.0' '26.1'
 '49.0' '38.0' '2200.0' '34.0' '869.0' '809.0' '814.0' '821.0' '0.9'
 '820.0' '832.0' '834.0' '123.0' '825.0' '831.0' '845.0' '5.5' '864.0'
 '847.0' '848.0' '849.0' '858.0' '868.0' '955.0' '3.4' '5.3' '5.7' '900.0'
 '914.0' '890.0' '882.0' '871.0' '872.0' '873.0' '883.0' '924.0' '934.0'
 '944.0' '610.0' '525.0' '947.0' '946.0' '965.0' '945.0' '967.0' '1019.0'
 '1020.0' '1037.0' '1006.0' '1075.0' '1099.0' '1067.0' '1066.0' '176600.0'
 '5.6' '1104.0' '1110.0' '1111.0' '1121.0' '190800.0' '570.0' '1112.0'
 '1143.0' '1115.0' '625.0' '852.0']

Unique values in SO4:
['220.0' '3.4' '275.0' '12.0' '47.0' '1.0' nan '1.2' '19.6' '6.0' '6.9'
 '14.2' '4.8' '7.1' '0.5' '8.0' '2.4' '49.0' '122.0' '152.0' '156.0'
 '100.0' '130.0' '108.0' '101.0' '48.0' '26.0' '147.0' '190.0' '216.0'
 '2.5' '107.0' '123.0' '81.0' '92.0' '120.0' '125.0' '103.0' '14.0' '20.0'
 '56.0' '88.0' '106.0' '110.0' '31.3' '89.0' '24.9' '138.0' '121.0'
 '126.0' '1.3' '35.0' '70.0' '155.0' '199.0' '129.0' '140.0' '102.0'
 '124.0' '323.0' '80.0' '196.0' '77.8' '2.0' '197.0' '76.0' '210.0'
 '456.0' '184.0' '143.0' '67.0' '96.7' '104.0' '187.0' '222.0' '84.0'
 '4300.0' '64.0' '1130.0' '8800.0' '10.0' '34.0' '47.6' '68.0' '315.0'
 '59.0' '43.0' '73.0' '75.0' '79.0' '1320.0' '53.0' '116.0' '97.0' '111.0'
 '4.6' '3.2' '127.0' '42.0' '105.0' '115.0' '10.7' '77.0' '144.0' '22.0'
 '78.0' '118.0' '112.0' '114.0' '3.3' '128.0' '18.0' '63.0' '94.0' '117.0'
 '98.0' '960.0' '1.5' '145.0' '52.0' '211.0' '4.5' '7.3' '66.0' '45.0'
 '38.0' '293.0' '60.0' '4.0' '36.0' '14.7' '250.0' '425.0' '3.0' '11.4'
 '44.0' '236.0' '620.0' '4900.0' '93.0' '191.0' '5.0' '50.0' '33.0'
 '213.0' '224.0' '532.0' '640.0' '229.0' '7.0' '29.0' '6100.0' '658.0'
 '360.0' '160.0' '11.0' '19.0' '41.0' '550.0' '198.0' '37.0' '474.0'
 '209.0' '320.0' '310.0' '496.0' '420.0' '13.0' '186.0' '580.0' '58.6'
 '1100.0' '180.0' '46.0' '26.9' '90.0' '2200.0' '69.0' '71.8' '72.0'
 '370.0' '169.0' '55.0' '74.0' '245.0' '329.0' '21.0' '57.0' '96.0' '87.7'
 '246.0' '27.0' '40.0' '327.0' '348.0' '9.0' '61.0' '457.0']

Total rows before filtering: 701
Total rows after filtering: 337
Rows removed: 364

First few rows of cleaned dataset:

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
0,California State 2-14 well,351.0,5.7,43700.0,13700.0,24000.0,29.0,120800.0,220.0
1,California State 2-14 well,351.0,5.3,50200.0,16700.0,26200.0,14.0,142600.0,3.4
2,California State 2-14 well,351.0,5.7,43200.0,14000.0,21600.0,35.0,176.0,275.0
26,NWIS Well 026S040E22P001M,300.0,8.6,410.0,4.9,1.8,0.5,11.0,12.0
27,NWIS Well 026S040E22P001M,300.0,8.7,17.0,6.0,55.0,15.0,68.0,47.0
28,California State 2-14 well,298.0,2.4,47400.0,14400.0,27240.0,36.0,132200.0,1.0
29,California State 2-14 well,298.0,4.3,43400.0,16900.0,28790.0,19.0,135500.0,NaN
48,California State 2-14 well,250.0,2.5,54600.0,21300.0,39050.0,52.0,174800.0,1.2
52,California State 2-14 well,244.0,8.2,2.0,1.0,3.0,1.0,1.0,19.6
53,California State 2-14 well,244.0,5.7,60500.0,18800.0,31100.0,38.0,164900.0,6.0

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
3007,Steamboat Well #4,90.3,6.5,75.0,2.2,1.6,NaN,15.0,45.0
3021,MOANA AREA - TERRIL WELL,90.0,7.7,203.0,7.4,29.0,0.8,42.0,348.0
3022,TERRIL WELL,90.0,7.7,203.0,7.4,29.0,0.8,1121.0,348.0
3047,Pilgrim Well #2,90.0,6.4,1600.0,63.0,530.0,1.0,3400.0,9.0
3085,Osborn Well,90.0,9.5,63.0,10.0,82.0,18.0,172.0,43.0
3089,UNNAMED WELL,90.0,5.9,370.0,32.0,35.0,0.1,570.0,52.0
3093,NWIS Well 15S 26E 23DDC1,90.0,7.7,1100.0,35.0,130.0,0.4,1112.0,61.0
3095,NWIS Well (A-13- 1)19cac- 1,90.0,NaN,550.0,40.0,56.0,0.2,1143.0,66.0
3120,MOANA AREA - OLD YATES WELL,90.0,8.3,243.0,7.4,23.0,0.2,50.0,457.0
3121,OLD YATES WELL,90.0,8.3,243.0,7.4,23.0,0.2,1115.0,457.0

In [25]:
df.columns.to_list()

['well_sample', 'temp_measured', 'pH', 'Na', 'K', 'Ca', 'Mg', 'Cl', 'SO4']

In [9]:
### Eliminate wells with temperature ≤ 150°C

original_len = len(df)

# Filter to keep only wells with temperature > 150
df = df[df['temp_measured'] <= 180]

print(f'Original number of rows: {original_len}')
print(f'Number of rows after filtering: {len(df)}')
print(f'Number of rows removed: {original_len - len(df)}')

print('\nSummary statistics for temperature after filtering:')
print(df['temp_measured'].describe())

print('\nFirst 5 rows of filtered dataset:')
display(df.head())
display(df.tail())

Original number of rows: 337
Number of rows after filtering: 309
Number of rows removed: 28

Summary statistics for temperature after filtering:
count    309.000000
mean     131.840453
std       31.690257
min       90.000000
25%       97.200000
50%      135.000000
75%      162.800000
max      178.000000
Name: temp_measured, dtype: float64

First 5 rows of filtered dataset:

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
180,Utah State 42-7 Well,178.0,10.0,53.2,4.4,86.0,31.0,37.0,147.0
192,NWIS Well 003S028E32E004M,174.0,8.6,48.0,10.0,160.0,42.0,250.0,190.0
197,Well 73B-7,173.9,9.0,499.7,74.2,8.4,< .01,46.0,216.0
198,Well 73B-7,173.9,5.9,0.9,0.3,0.1,< .01,45.0,2.5
199,NWIS Well 003S028E32E004M,173.9,7.1,350.0,36.0,6.9,0.2,44.0,107.0

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
3089,UNNAMED WELL,90.0,5.9,370.0,32.0,35.0,0.1,570.0,52.0
3093,NWIS Well 15S 26E 23DDC1,90.0,7.7,1100.0,35.0,130.0,0.4,1112.0,61.0
3095,NWIS Well (A-13- 1)19cac- 1,90.0,NaN,550.0,40.0,56.0,0.2,1143.0,66.0
3120,MOANA AREA - OLD YATES WELL,90.0,8.3,243.0,7.4,23.0,0.2,50.0,457.0
3121,OLD YATES WELL,90.0,8.3,243.0,7.4,23.0,0.2,1115.0,457.0

In [10]:
### Display groups of samples with the same name

# Get counts of each unique name
name_counts = df['well_sample'].value_counts()

# Filter for names that appear more than once
duplicate_names = name_counts[name_counts > 1]

print(f"Number of names that appear multiple times: {len(duplicate_names)}")
print("\nNames and their occurrence counts:")
print(duplicate_names)

print("\nDetailed view of each group:")
for name in duplicate_names.index:
    print(f"\n{'='*50}")
    print(f"Group: {name} (appears {name_counts[name]} times)")
    print(f"{'='*50}")
    display(df[df['well_sample'] == name])

Number of names that appear multiple times: 52

Names and their occurrence counts:
well_sample
NWIS Well 003S028E32E006M                              19
Henderson Well. Pleasant Valley                        14
NWIS Well 15S 26E 23BBC1                               13
NWIS Well 003S028E32E005M                              12
USGS Drill Hole Well GS-1. Steamboat Gaging Station     7
Y.C. well 21-5                                          6
Y.C. well 23-5                                          5
NWIS Well 003S028E32E004M                               5
Steamboat Well #4                                       5
NWIS Well  (C-36-15)20bbc- 1                            4
Amor II well 43-21                                      4
DARROUGH'S WELL                                         3
SHALLOW RESEARCH WELL (SODA LAKE). 4                    3
G. FILIPPINI WELL NO. 1                                 3
FLOWING WELL IN STILLWATER                              3
NDOT Well                                               3
FLY RANCH WELL                                          3
Fly Ranch Hot Well. Hualapai Flat                       3
PW3-1-C well                                            2
Antelope Canyon Well. Rye Patch KGRA                    2
PW2-1-B well                                            2
PW2-1-A well                                            2
GEYSER WELL NO. 32                                      2
PW3-3-B well                                            2
Bacon Flat 24-17 oil well                               2
PW3-2-A well                                            2
Chevron Well 1-29. Soda Lake KGRA                       2
PW2-3-B well                                            2
PW2-4-B well                                            2
NV Oil and Minerals Well 1. The Crossing                2
Y.C. well 83A-6                                         2
FLY RANCH WELL - WESTERN GEOTHERMAL                     2
NWIS Well 022S039E04P001M                               2
PW2-4-A well                                            2
PW3-4-A well                                            2
PW2-5-B well                                            2
NWIS Well 15S 26E 23DDC1                                2
Well 73B-7                                              2
PW3-4-B well                                            2
Steamboat/Ormat Well                                    2
Florida Canyon Mine well                                2
BRINE WELL                                              2
Pilgrim Well #2                                         2
NWIS Well 15S 26E 23CAA1                                2
Well 28-33                                              2
NWIS Well 002  N46 E28 13B   4                          2
North Injection Well DF 45-14. Boyer Ranch              2
SURPRISE VALLEY MINERAL WELL                            2
PW2-5-A well                                            2
PW3-2-B well                                            2
101 Separator. 3 Wells                                  2
NWIS Well 003S029E30E001M                               2
Name: count, dtype: int64

Detailed view of each group:

==================================================
Group: NWIS Well 003S028E32E006M (appears 19 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
238,NWIS Well 003S028E32E006M,171.1,6.2,330.0,36.0,5.3,0.2,68.0,120.0
239,NWIS Well 003S028E32E006M,171.1,6.3,360.0,33.0,2.5,0.6,63.0,120.0
240,NWIS Well 003S028E32E006M,171.1,6.2,360.0,32.0,4.7,0.4,64.0,120.0
254,NWIS Well 003S028E32E006M,171.0,6.3,28.0,6.3,14.0,2.8,15.0,14.0
255,NWIS Well 003S028E32E006M,171.0,6.2,8.4,4.0,49.0,17.0,5.1,20.0
257,NWIS Well 003S028E32E006M,171.0,6.1,610.0,77.0,2.3,0.2,810.0,88.0
259,NWIS Well 003S028E32E006M,171.0,6.1,665.0,87.0,9.2,0.0,889.0,103.0
281,NWIS Well 003S028E32E006M,170.0,6.6,330.0,36.0,6.7,0.2,85.0,110.0
284,NWIS Well 003S028E32E006M,170.0,6.3,330.0,30.0,5.7,0.1,82.0,110.0
297,NWIS Well 003S028E32E006M,170.0,6.5,1420.0,133.0,70.0,2.2,2340.0,NaN
330,NWIS Well 003S028E32E006M,169.0,6.6,741.0,91.0,6.0,NaN,922.0,138.0
337,NWIS Well 003S028E32E006M,168.9,6.6,340.0,22.0,5.8,0.2,100.0,110.0
356,NWIS Well 003S028E32E006M,168.0,6.5,49.0,0.4,2.8,1.0,5.4,35.0
360,NWIS Well 003S028E32E006M,168.0,6.3,197.0,18.0,2.2,0.8,106.0,70.0
381,NWIS Well 003S028E32E006M,167.8,6.3,330.0,30.0,2.1,0.2,118.0,110.0
382,NWIS Well 003S028E32E006M,167.8,6.5,320.0,33.0,2.6,0.1,115.0,140.0
387,NWIS Well 003S028E32E006M,167.8,6.6,350.0,30.0,2.9,0.1,116.0,120.0
531,NWIS Well 003S028E32E006M,162.8,6.3,330.0,30.0,5.9,0.3,181.0,110.0
556,NWIS Well 003S028E32E006M,161.1,6.5,330.0,31.0,7.4,< .02,200.0,110.0

==================================================
Group: Henderson Well. Pleasant Valley (appears 14 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
1357,Henderson Well. Pleasant Valley,114.0,6.7,12.0,5.0,21.0,7.0,3.0,4.0
1360,Henderson Well. Pleasant Valley,114.0,6.8,245.0,19.0,15.0,1.0,195.0,36.0
1361,Henderson Well. Pleasant Valley,114.0,7.2,150.0,15.0,20.0,2.3,72.0,140.0
1377,Henderson Well. Pleasant Valley,113.0,8.0,3.5,0.8,67.1,18.8,5.4,14.7
1382,Henderson Well. Pleasant Valley,113.0,7.1,45.0,6.8,55.0,23.0,41.0,64.0
1383,Henderson Well. Pleasant Valley,113.0,NaN,67.0,5.5,120.0,42.0,190.0,70.0
1438,Henderson Well. Pleasant Valley,112.0,7.5,17.0,3.8,18.0,6.4,8.4,11.4
1442,Henderson Well. Pleasant Valley,112.0,7.1,50.0,1.6,42.0,6.0,53.0,44.0
1446,Henderson Well. Pleasant Valley,112.0,6.5,186.0,8.2,10.0,0.3,47.0,236.0
1447,Henderson Well. Pleasant Valley,112.0,7.8,560.0,6.3,150.0,130.0,830.0,620.0
1448,Henderson Well. Pleasant Valley,112.0,8.0,100000.0,2100.0,1300.0,2300.0,170000.0,4900.0
1476,Henderson Well. Pleasant Valley,111.0,7.9,364.0,7.9,104.0,60.1,617.0,191.0
1487,Henderson Well. Pleasant Valley,110.0,7.6,5.5,3.4,14.0,8.2,0.6,3.0
1537,Henderson Well. Pleasant Valley,109.0,8.0,35.0,NaN,22.0,3.0,60.0,33.0

==================================================
Group: NWIS Well 15S 26E 23BBC1 (appears 13 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
2125,NWIS Well 15S 26E 23BBC1,95.0,7.4,510.0,20.0,51.0,0.2,821.0,69.0
2139,NWIS Well 15S 26E 23BBC1,95.0,7.4,53.0,NaN,2.0,4.0,5.0,14.0
2163,NWIS Well 15S 26E 23BBC1,95.0,7.9,541.0,20.0,51.0,0.2,820.0,56.0
2233,NWIS Well 15S 26E 23BBC1,94.5,NaN,20.0,1.1,59.8,13.3,4.0,71.8
2234,NWIS Well 15S 26E 23BBC1,94.5,NaN,20.0,1.0,66.0,14.0,5.5,72.0
2235,NWIS Well 15S 26E 23BBC1,94.5,NaN,19.0,1.2,64.0,14.0,5.1,73.0
2299,NWIS Well 15S 26E 23BBC1,94.0,NaN,21.0,1.0,69.0,14.0,6.0,77.0
2319,NWIS Well 15S 26E 23BBC1,94.0,NaN,21.0,1.2,68.0,15.0,3.4,72.0
2321,NWIS Well 15S 26E 23BBC1,94.0,NaN,19.0,1.0,69.0,15.0,5.3,74.0
2322,NWIS Well 15S 26E 23BBC1,94.0,NaN,21.0,1.1,68.0,14.0,5.7,74.0
2544,NWIS Well 15S 26E 23BBC1,93.0,7.4,65.0,NaN,3.0,1.0,5.0,21.0
2629,NWIS Well 15S 26E 23BBC1,92.8,7.4,560.0,22.0,53.0,0.4,946.0,57.0
2671,NWIS Well 15S 26E 23BBC1,92.5,NaN,22.0,1.2,96.0,17.0,16.0,96.0

==================================================
Group: NWIS Well 003S028E32E005M (appears 12 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
384,NWIS Well 003S028E32E005M,167.8,6.3,370.0,34.0,2.6,0.6,114.0,130.0
404,NWIS Well 003S028E32E005M,167.0,6.2,792.0,60.0,38.0,38.0,860.0,323.0
475,NWIS Well 003S028E32E005M,164.0,6.6,806.0,77.0,13.0,NaN,996.0,130.0
477,NWIS Well 003S028E32E005M,164.0,6.6,450.0,22.0,45.0,0.2,383.0,456.0
482,NWIS Well 003S028E32E005M,163.9,6.6,340.0,24.0,4.7,0.1,165.0,120.0
483,NWIS Well 003S028E32E005M,163.9,6.7,360.0,30.0,4.9,0.0,166.0,120.0
503,NWIS Well 003S028E32E005M,163.0,6.7,150.0,34.0,224.0,41.2,554.0,96.7
532,NWIS Well 003S028E32E005M,162.8,6.4,330.0,30.0,5.7,0.3,180.0,110.0
533,NWIS Well 003S028E32E005M,162.8,6.8,350.0,23.0,5.3,0.1,178.0,120.0
585,NWIS Well 003S028E32E005M,160.0,7.0,340.0,NaN,5.1,0.2,211.0,120.0
634,NWIS Well 003S028E32E005M,158.0,6.8,322.0,27.0,15.0,0.0,350.0,75.0
639,NWIS Well 003S028E32E005M,157.8,6.8,360.0,30.0,7.9,0.1,231.0,120.0

==================================================
Group: USGS Drill Hole Well GS-1. Steamboat Gaging Station (appears 7 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
654,USGS Drill Hole Well GS-1. Steamboat Gaging St...,156.7,6.5,52.0,16.0,62.0,14.0,13.0,53.0
707,USGS Drill Hole Well GS-1. Steamboat Gaging St...,154.8,9.8,57.0,6.1,64.0,28.0,30.0,77.0
720,USGS Drill Hole Well GS-1. Steamboat Gaging St...,154.0,6.4,68.0,7.4,46.0,21.0,21.0,78.0
724,USGS Drill Hole Well GS-1. Steamboat Gaging St...,154.0,6.6,665.0,69.0,7.8,1.2,889.0,118.0
1067,USGS Drill Hole Well GS-1. Steamboat Gaging St...,130.0,10.0,39.0,5.2,62.0,57.0,42.0,70.0
1241,USGS Drill Hole Well GS-1. Steamboat Gaging St...,122.2,11.2,43.0,8.4,80.0,11.0,30.0,52.0
1374,USGS Drill Hole Well GS-1. Steamboat Gaging St...,113.7,6.3,40.0,5.8,14.0,2.5,6.4,22.0

==================================================
Group: Y.C. well 21-5 (appears 6 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
690,Y.C. well 21-5,155.0,8.4,688.0,64.0,2.1,< .02,254.0,127.0
694,Y.C. well 21-5,155.0,3.8,2200.0,255.0,81.0,0.1,3600.0,105.0
698,Y.C. well 21-5,155.0,4.3,200.0,2.4,6.9,0.3,65.0,220.0
734,Y.C. well 21-5,153.9,8.2,639.0,62.1,2.8,0.0,266.0,130.0
748,Y.C. well 21-5,153.5,4.5,8.2,2.2,16.0,2.3,0.7,3.3
749,Y.C. well 21-5,153.3,4.9,0.2,0.1,0.3,< .01,279.0,1.2

==================================================
Group: Y.C. well 23-5 (appears 5 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
308,Y.C. well 23-5,169.5,3.5,385.0,36.0,4.4,0.0,305.0,125.0
309,Y.C. well 23-5,169.4,5.9,168.0,22.0,0.4,< .02,91.0,24.9
350,Y.C. well 23-5,168.3,5.3,0.9,0.2,0.4,0.0,110.0,1.3
366,Y.C. well 23-5,168.0,7.7,70.0,4.2,25.0,18.0,7.6,NaN
380,Y.C. well 23-5,167.8,7.9,692.0,86.3,2.7,0.1,119.0,129.0

==================================================
Group: NWIS Well 003S028E32E004M (appears 5 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
192,NWIS Well 003S028E32E004M,174.0,8.6,48.0,10.0,160.0,42.0,250.0,190.0
199,NWIS Well 003S028E32E004M,173.9,7.1,350.0,36.0,6.9,0.2,44.0,107.0
200,NWIS Well 003S028E32E004M,173.9,8.8,370.0,40.0,1.6,0.2,43.0,122.0
213,NWIS Well 003S028E32E004M,172.2,6.5,340.0,36.0,3.9,0.1,52.0,130.0
214,NWIS Well 003S028E32E004M,172.2,6.6,360.0,31.0,4.2,0.1,53.0,120.0

==================================================
Group: Steamboat Well #4 (appears 5 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
1639,Steamboat Well #4,103.3,7.3,42.0,5.5,56.0,12.0,20.0,38.0
1783,Steamboat Well #4,98.1,7.8,44.0,4.3,60.0,25.0,60.0,26.0
1948,Steamboat Well #4,96.7,6.5,637.0,61.0,16.0,1.0,824.0,107.0
1969,Steamboat Well #4,96.3,6.4,127.0,5.5,12.0,1.0,17.0,156.0
3007,Steamboat Well #4,90.3,6.5,75.0,2.2,1.6,NaN,15.0,45.0

==================================================
Group: NWIS Well  (C-36-15)20bbc- 1 (appears 4 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
1708,NWIS Well (C-36-15)20bbc- 1,100.0,7.3,135.0,7.7,32.0,1.0,172.0,41.0
1724,NWIS Well (C-36-15)20bbc- 1,100.0,7.3,260.0,14.0,52.0,1.3,694.0,550.0
1881,NWIS Well (C-36-15)20bbc- 1,97.2,7.6,270.0,21.0,58.0,0.4,743.0,580.0
1934,NWIS Well (C-36-15)20bbc- 1,97.0,7.6,650.0,51.0,460.0,180.0,1400.0,1100.0

==================================================
Group: Amor II well 43-21 (appears 4 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
992,Amor II well 43-21,135.0,NaN,1298.0,110.0,140.0,0.2,2225.0,211.0
993,Amor II well 43-21,135.0,NaN,1298.0,110.0,140.0,0.2,378.0,211.0
994,Amor II well 43-21,135.0,NaN,1400.0,120.0,148.0,0.2,2320.0,220.0
995,Amor II well 43-21,135.0,NaN,1400.0,120.0,148.0,0.2,377.0,220.0

==================================================
Group: DARROUGH'S WELL (appears 3 times)
==================================================

          well_sample  temp_measured   pH    Na    K   Ca     Mg      Cl   SO4
2989  DARROUGH'S WELL           90.6  8.8  99.0  3.3  1.1  < .05  1104.0  47.0
2998  DARROUGH'S WELL           90.5  8.8  99.0  3.3  1.1    0.1    12.0  47.0
2999  DARROUGH'S WELL           90.5  8.8  99.0  3.3  1.1   0.05    12.0  47.0

==================================================
Group: SHALLOW RESEARCH WELL (SODA LAKE). 4 (appears 3 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
1686,SHALLOW RESEARCH WELL (SODA LAKE). 4,100.0,7.9,1000.0,48.0,82.0,2.1,1500.0,360.0
1687,SHALLOW RESEARCH WELL (SODA LAKE). 4,100.0,7.9,1000.0,48.0,82.0,2.1,695.0,360.0
1723,SHALLOW RESEARCH WELL (SODA LAKE). 4,100.0,7.9,1000.0,48.0,82.0,2.1,1500.0,360.0

==================================================
Group: G. FILIPPINI WELL NO. 1 (appears 3 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
2282,G. FILIPPINI WELL NO. 1,94.2,8.0,450.0,13.0,39.0,0.1,540.0,370.0
2491,G. FILIPPINI WELL NO. 1,93.3,7.9,461.0,18.0,46.0,0.4,610.0,224.0
2494,G. FILIPPINI WELL NO. 1,93.3,8.0,467.0,15.0,40.0,1.5,525.0,329.0

==================================================
Group: FLOWING WELL IN STILLWATER (appears 3 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
1991,FLOWING WELL IN STILLWATER,96.1,7.6,1480.0,42.0,108.0,1.7,779.0,190.0
2036,FLOWING WELL IN STILLWATER,96.0,7.6,1480.0,42.0,108.0,1.7,2200.0,190.0
2038,FLOWING WELL IN STILLWATER,96.0,7.6,1480.0,42.0,108.0,1.7,2200.0,190.0

==================================================
Group: NDOT Well (appears 3 times)
==================================================

     well_sample  temp_measured   pH     Na     K    Ca    Mg     Cl   SO4
287    NDOT Well          170.0  7.9  223.0  11.7  70.4  33.0  436.0  31.3
587    NDOT Well          160.0  7.8   14.0  10.0  43.0  20.0    9.7  10.0
2979   NDOT Well           90.6  8.1   17.0   1.6  47.0  12.0   15.0  21.0

==================================================
Group: FLY RANCH WELL (appears 3 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
1980,FLY RANCH WELL,96.1,8.4,386.0,17.0,22.0,0.2,780.0,46.0
2394,FLY RANCH WELL,93.9,7.2,405.0,18.0,22.0,0.2,882.0,245.0
2901,FLY RANCH WELL,91.1,7.2,400.0,18.0,28.0,0.2,1067.0,NaN

==================================================
Group: Fly Ranch Hot Well. Hualapai Flat (appears 3 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
1889,Fly Ranch Hot Well. Hualapai Flat,97.2,NaN,29.4,10.6,103.0,85.0,21.1,58.6
1892,Fly Ranch Hot Well. Hualapai Flat,97.2,NaN,38.4,6.9,104.0,57.7,43.3,81.0
1997,Fly Ranch Hot Well. Hualapai Flat,96.1,8.4,18.7,6.8,95.8,13.7,26.1,26.9

==================================================
Group: PW3-1-C well (appears 2 times)
==================================================

      well_sample  temp_measured   pH     Na     K    Ca    Mg     Cl    SO4
515  PW3-1-C well          163.0  6.3  276.0  27.0  58.0  18.0   36.0  222.0
536  PW3-1-C well          162.8  6.3  654.0  49.0  15.2   0.5  194.0  126.0

==================================================
Group: Antelope Canyon Well. Rye Patch KGRA (appears 2 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
522,Antelope Canyon Well. Rye Patch KGRA,162.8,NaN,40.0,5.7,83.0,30.0,95.0,84.0
524,Antelope Canyon Well. Rye Patch KGRA,162.8,NaN,110000.0,7000.0,1300.0,3000.0,190000.0,4300.0

==================================================
Group: PW2-1-B well (appears 2 times)
==================================================

      well_sample  temp_measured   pH     Na     K    Ca   Mg     Cl    SO4
514  PW2-1-B well          163.0  6.6  347.0  17.0  33.0  4.6  244.0  187.0
540  PW2-1-B well          162.8  6.6  626.0  53.0  14.8  0.3  190.0    NaN

==================================================
Group: PW2-1-A well (appears 2 times)
==================================================

      well_sample  temp_measured   pH     Na     K    Ca   Mg     Cl    SO4
504  PW2-1-A well          163.0  5.9  295.0  33.0  43.0  5.2   29.0  104.0
535  PW2-1-A well          162.8  5.9  610.0  53.0  18.3  0.4  185.0  124.0

==================================================
Group: GEYSER WELL NO. 32 (appears 2 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
2170,GEYSER WELL NO. 32,95.0,7.4,667.0,63.0,15.0,1.0,832.0,122.0
2172,GEYSER WELL NO. 32,95.0,8.7,728.0,66.0,11.0,1.4,834.0,128.0

==================================================
Group: PW3-3-B well (appears 2 times)
==================================================

      well_sample  temp_measured   pH     Na     K    Ca   Mg     Cl    SO4
547  PW3-3-B well          162.2  6.1  646.0  50.0  14.8  0.3  197.0  126.0
550  PW3-3-B well          162.0  6.1  628.0  54.0  15.8  0.4  801.0  125.0

==================================================
Group: Bacon Flat 24-17 oil well (appears 2 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
1386,Bacon Flat 24-17 oil well,113.0,9.0,1680.0,18.0,7.1,5.4,937.0,425.0
1402,Bacon Flat 24-17 oil well,112.8,9.0,1680.0,18.0,7.1,5.4,553.0,425.0

==================================================
Group: PW3-2-A well (appears 2 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
559,PW3-2-A well,161.1,5.9,635.0,54.0,18.5,1.0,208.0,129.0
575,PW3-2-A well,161.0,5.9,1900.0,4.2,590.0,760.0,1000.0,8800.0

==================================================
Group: Chevron Well 1-29. Soda Lake KGRA (appears 2 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
588,Chevron Well 1-29. Soda Lake KGRA,160.0,8.4,22.0,4.6,69.0,10.0,57.0,34.0
1041,Chevron Well 1-29. Soda Lake KGRA,132.0,5.7,230.0,16.0,1.0,NaN,69.0,130.0

==================================================
Group: PW2-3-B well (appears 2 times)
==================================================

      well_sample  temp_measured   pH     Na     K    Ca    Mg     Cl    SO4
591  PW2-3-B well          160.0  6.3   19.0   NaN  51.0  23.0    7.5   68.0
594  PW2-3-B well          160.0  6.3  612.0  52.0  15.4   0.3  218.0  121.0

==================================================
Group: PW2-4-B well (appears 2 times)
==================================================

      well_sample  temp_measured   pH     Na     K    Ca   Mg     Cl    SO4
879  PW2-4-B well          145.0  6.1  694.0  79.0  10.0  0.0  902.0  117.0
881  PW2-4-B well          145.0  6.1  636.0  46.0  20.0  0.5  333.0  120.0

==================================================
Group: NV Oil and Minerals Well 1. The Crossing (appears 2 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
623,NV Oil and Minerals Well 1. The Crossing,158.8,NaN,29.0,7.3,78.0,38.0,31.0,43.0
624,NV Oil and Minerals Well 1. The Crossing,158.8,NaN,40.0,5.2,65.0,24.0,55.0,73.0

==================================================
Group: Y.C. well 83A-6 (appears 2 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
661,Y.C. well 83A-6,156.1,8.2,670.0,80.0,3.6,< .02,243.0,116.0
670,Y.C. well 83A-6,156.0,8.3,5.4,0.5,70.3,20.3,11.2,4.6

==================================================
Group: FLY RANCH WELL - WESTERN GEOTHERMAL (appears 2 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
1878,FLY RANCH WELL - WESTERN GEOTHERMAL,97.2,NaN,335.0,14.0,33.0,4.1,752.0,186.0
1879,FLY RANCH WELL - WESTERN GEOTHERMAL,97.2,NaN,347.0,17.0,33.0,4.6,757.0,187.0

==================================================
Group: NWIS Well 022S039E04P001M (appears 2 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
1861,NWIS Well 022S039E04P001M,97.3,7.4,720.0,56.0,150.0,89.0,1100.0,420.0
1872,NWIS Well 022S039E04P001M,97.2,7.4,19.0,9.4,3.0,1.0,746.0,13.0

==================================================
Group: PW2-4-A well (appears 2 times)
==================================================

      well_sample  temp_measured   pH     Na     K    Ca    Mg     Cl    SO4
829  PW2-4-A well          148.0  5.9  143.0  11.8  31.0  15.0   29.0   63.0
833  PW2-4-A well          147.8  5.9  630.0  51.0  21.6   0.5  313.0  123.0

==================================================
Group: PW3-4-A well (appears 2 times)
==================================================

      well_sample  temp_measured   pH     Na     K    Ca   Mg     Cl    SO4
506  PW3-4-A well          163.0  5.9  675.0  28.0   5.0  6.0   65.0  120.0
534  PW3-4-A well          162.8  5.9  620.0  52.0  15.9  0.4  183.0  124.0

==================================================
Group: PW2-5-B well (appears 2 times)
==================================================

      well_sample  temp_measured   pH     Na     K    Ca   Mg     Cl    SO4
476  PW2-5-B well          164.0  6.2  180.0   8.2  25.0  4.5  110.0  210.0
486  PW2-5-B well          163.9  6.2  643.0  53.0  14.5  0.4  169.0  125.0

==================================================
Group: NWIS Well 15S 26E 23DDC1 (appears 2 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
2611,NWIS Well 15S 26E 23DDC1,92.8,7.9,1000.0,29.0,120.0,0.3,947.0,60.0
3093,NWIS Well 15S 26E 23DDC1,90.0,7.7,1100.0,35.0,130.0,0.4,1112.0,61.0

==================================================
Group: Well 73B-7  (appears 2 times)
==================================================

     well_sample  temp_measured   pH     Na     K   Ca     Mg    Cl    SO4
197  Well 73B-7           173.9  9.0  499.7  74.2  8.4  < .01  46.0  216.0
198  Well 73B-7           173.9  5.9    0.9   0.3  0.1  < .01  45.0    2.5

==================================================
Group: PW3-4-B well (appears 2 times)
==================================================

      well_sample  temp_measured   pH     Na     K    Ca   Mg     Cl    SO4
206  PW3-4-B well          173.0  6.1  620.0  51.0  16.6  0.4  794.0  123.0
210  PW3-4-B well          172.8  6.1  653.0  48.0  15.0  0.4   48.0    NaN

==================================================
Group: Steamboat/Ormat Well (appears 2 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
1384,Steamboat/Ormat Well,113.0,6.3,611.0,58.0,15.0,0.3,790.0,120.0
1401,Steamboat/Ormat Well,112.8,6.3,611.0,58.0,15.0,0.3,554.0,120.0

==================================================
Group: Florida Canyon Mine well (appears 2 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
1345,Florida Canyon Mine well,114.4,NaN,1350.0,240.0,120.0,4.0,539.0,18.0
1351,Florida Canyon Mine well,114.4,NaN,1350.0,240.0,120.0,4.0,2250.0,18.0

==================================================
Group: BRINE WELL (appears 2 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
1585,BRINE WELL,107.2,5.9,71000.0,6380.0,45000.0,3840.0,211000.0,532.0
1586,BRINE WELL,107.2,6.0,70700.0,5950.0,46900.0,1860.0,219600.0,640.0

==================================================
Group: Pilgrim Well #2  (appears 2 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
2997,Pilgrim Well #2,90.5,6.4,1550.0,64.0,530.0,1.0,3400.0,10.0
3047,Pilgrim Well #2,90.0,6.4,1600.0,63.0,530.0,1.0,3400.0,9.0

==================================================
Group: NWIS Well 15S 26E 23CAA1 (appears 2 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
2873,NWIS Well 15S 26E 23CAA1,91.1,8.2,530.0,39.0,54.0,0.1,1075.0,67.0
2933,NWIS Well 15S 26E 23CAA1,91.0,8.2,120.0,3.4,3.6,NaN,82.0,40.0

==================================================
Group: Well 28-33  (appears 2 times)
==================================================

     well_sample  temp_measured   pH     Na     K   Ca     Mg     Cl    SO4
379  Well 28-33           167.8  9.0  446.5  67.8  7.5  < .01  122.0  199.0
383  Well 28-33           167.8  5.8    0.9   0.3  0.1    0.0  130.0    2.5

==================================================
Group: NWIS Well 002  N46 E28 13B   4 (appears 2 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
2686,NWIS Well 002 N46 E28 13B 4,92.2,8.4,180.0,8.0,9.6,0.2,1020.0,48.0
2750,NWIS Well 002 N46 E28 13B 4,92.0,8.4,20.0,9.1,43.0,15.0,20.0,18.0

==================================================
Group: North Injection Well DF 45-14. Boyer Ranch (appears 2 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
1195,North Injection Well DF 45-14. Boyer Ranch,125.0,7.1,46.0,7.2,56.0,24.0,43.0,66.0
1590,North Injection Well DF 45-14. Boyer Ranch,107.0,9.2,108.0,4.9,78.2,65.1,103.0,229.0

==================================================
Group: SURPRISE VALLEY MINERAL WELL (appears 2 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
1784,SURPRISE VALLEY MINERAL WELL,98.1,8.4,280.0,5.5,16.0,0.1,200.0,320.0
1804,SURPRISE VALLEY MINERAL WELL,98.0,NaN,297.0,6.0,17.0,0.1,198.0,310.0

==================================================
Group: PW2-5-A well (appears 2 times)
==================================================

      well_sample  temp_measured   pH     Na     K    Ca   Mg     Cl    SO4
471  PW2-5-A well          164.0  5.9  250.0  34.0  45.0  4.9   29.0  110.0
485  PW2-5-A well          163.9  5.9  607.0  53.0  17.5  1.2  170.0  124.0

==================================================
Group: PW3-2-B well (appears 2 times)
==================================================

      well_sample  temp_measured   pH     Na     K    Ca    Mg     Cl    SO4
401  PW3-2-B well          167.2  6.2  641.0  49.0  15.7   0.4  134.0    NaN
407  PW3-2-B well          167.0  6.2  570.0  19.0  62.0  27.0  235.0  102.0

==================================================
Group: 101 Separator. 3 Wells (appears 2 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
416,101 Separator. 3 Wells,166.1,9.2,407.0,64.0,8.0,0.0,141.0,196.0
418,101 Separator. 3 Wells,166.1,6.0,1.0,1.3,0.2,0.0,140.0,2.0

==================================================
Group: NWIS Well 003S029E30E001M (appears 2 times)
==================================================

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
2457,NWIS Well 003S029E30E001M,93.3,8.9,340.0,21.0,16.0,0.4,924.0,93.0
2489,NWIS Well 003S029E30E001M,93.3,8.1,210.0,1.7,15.0,4.0,120.0,110.0

In [11]:
### Eliminate all samples with duplicate well names

original_len = len(df)

name_counts = df['well_sample'].value_counts()

# Filter for names that appear more than once
duplicate_names = name_counts[name_counts > 1]

print(f"Number of names that appear multiple times: {len(duplicate_names)}")
print("\nNames and their occurrence counts:")
print(duplicate_names)

# Remove all rows where well_sample appears more than once
df = df[~df['well_sample'].isin(duplicate_names.index)]

print(f'\nOriginal number of rows: {original_len}')
print(f'Number of rows after removing duplicates: {len(df)}')
print(f'Number of rows removed: {original_len - len(df)}')

# Verify no duplicates remain
remaining_duplicates = df['well_sample'].value_counts()
remaining_duplicates = remaining_duplicates[remaining_duplicates > 1]
print(f'\nRemaining duplicate well names: {len(remaining_duplicates)}')

print('\nFirst 5 rows of cleaned dataset:')
display(df.head())
display(df.tail())

Number of names that appear multiple times: 52

Names and their occurrence counts:
well_sample
NWIS Well 003S028E32E006M                              19
Henderson Well. Pleasant Valley                        14
NWIS Well 15S 26E 23BBC1                               13
NWIS Well 003S028E32E005M                              12
USGS Drill Hole Well GS-1. Steamboat Gaging Station     7
Y.C. well 21-5                                          6
Y.C. well 23-5                                          5
NWIS Well 003S028E32E004M                               5
Steamboat Well #4                                       5
NWIS Well  (C-36-15)20bbc- 1                            4
Amor II well 43-21                                      4
DARROUGH'S WELL                                         3
SHALLOW RESEARCH WELL (SODA LAKE). 4                    3
G. FILIPPINI WELL NO. 1                                 3
FLOWING WELL IN STILLWATER                              3
NDOT Well                                               3
FLY RANCH WELL                                          3
Fly Ranch Hot Well. Hualapai Flat                       3
PW3-1-C well                                            2
Antelope Canyon Well. Rye Patch KGRA                    2
PW2-1-B well                                            2
PW2-1-A well                                            2
GEYSER WELL NO. 32                                      2
PW3-3-B well                                            2
Bacon Flat 24-17 oil well                               2
PW3-2-A well                                            2
Chevron Well 1-29. Soda Lake KGRA                       2
PW2-3-B well                                            2
PW2-4-B well                                            2
NV Oil and Minerals Well 1. The Crossing                2
Y.C. well 83A-6                                         2
FLY RANCH WELL - WESTERN GEOTHERMAL                     2
NWIS Well 022S039E04P001M                               2
PW2-4-A well                                            2
PW3-4-A well                                            2
PW2-5-B well                                            2
NWIS Well 15S 26E 23DDC1                                2
Well 73B-7                                              2
PW3-4-B well                                            2
Steamboat/Ormat Well                                    2
Florida Canyon Mine well                                2
BRINE WELL                                              2
Pilgrim Well #2                                         2
NWIS Well 15S 26E 23CAA1                                2
Well 28-33                                              2
NWIS Well 002  N46 E28 13B   4                          2
North Injection Well DF 45-14. Boyer Ranch              2
SURPRISE VALLEY MINERAL WELL                            2
PW2-5-A well                                            2
PW3-2-B well                                            2
101 Separator. 3 Wells                                  2
NWIS Well 003S029E30E001M                               2
Name: count, dtype: int64

Original number of rows: 309
Number of rows after removing duplicates: 126
Number of rows removed: 183

Remaining duplicate well names: 0

First 5 rows of cleaned dataset:

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
180,Utah State 42-7 Well,178.0,10.0,53.2,4.4,86.0,31.0,37.0,147.0
208,Well 23-5-C-Recalc.,172.8,8.3,594.0,79.0,3.0,0.0,50.0,81.0
209,Well 23-5-C,172.8,8.3,673.0,90.0,3.4,0.1,51.0,92.0
215,PW-3-A well,172.2,6.2,627.0,56.0,14.5,0.2,54.0,125.0
241,Well 23-5-E-Recalc.,171.1,7.8,593.0,78.0,8.2,0.0,72.0,92.0

,well_sample,temp_measured,pH,Na,K,Ca,Mg,Cl,SO4
3085,Osborn Well,90.0,9.5,63.0,10.0,82.0,18.0,172.0,43.0
3089,UNNAMED WELL,90.0,5.9,370.0,32.0,35.0,0.1,570.0,52.0
3095,NWIS Well (A-13- 1)19cac- 1,90.0,NaN,550.0,40.0,56.0,0.2,1143.0,66.0
3120,MOANA AREA - OLD YATES WELL,90.0,8.3,243.0,7.4,23.0,0.2,50.0,457.0
3121,OLD YATES WELL,90.0,8.3,243.0,7.4,23.0,0.2,1115.0,457.0

In [12]:
col_to_check = ['pH', 'Na', 'K', 'Ca', 'Mg', 'Cl', 'SO4']

for col in col_to_check:
    print(f"Uniques value in {col}")
    print(df[col].unique())

Uniques value in pH
['10.0' '8.3' '6.2' '7.8' '5.4' '5.8' '5.7' '7.4' '6.4' '5.9' '6.3' '9.0'
 '7.2' nan '8.0' '6.1' '8.2' '6.0' '8.5' '7.1' '8.1' '4.8' '7.6' '8.4'
 '9.3' '8.9' '8.7' '9.2' '9.5' '9.6' '8.6' '9.9' '7.9' '6.6' '9.4' '7.3'
 '9.7' '4.5' '9.8' '7.7']
Uniques value in Na
['53.2' '594.0' '673.0' '627.0' '593.0' '665.0' '600.0' '610.0' '691.0'
 '611.0' '624.0' '660.0' '604.0' '692.0' '636.0' '628.0' '613.0' '95.5'
 '644.0' '429.0' '615.0' '330.0' '52.0' '631.0' '633.0' '605.0' '980.0'
 '637.0' '135.0' '630.0' '19.0' '2230.0' '646.0' '560.0' '590.0' '639.0'
 '655.0' '608.0' '4.2' '15.0' '586.0' '569.0' '657.0' '614.0' '625.0'
 '686.0' '390.0' '547.0' '626.0' '623.0' '56.0' '640.0' '4700.0' '0.3'
 '840.0' '7.6' '8.4' '584.0' '690.0' '493.0' '596.0' '81.0' '1760.0'
 '1050.0' '62.0' '9.1' '497.0' '470.0' '506.0' '499.0' '63000.0' '332.0'
 '263.0' '1000.0' '74600.0' '185.0' '29.0' '55.0' '370.0' '450.0' '5470.0'
 '324.0' '298.0' '24.0' '193.0' '641.0' '180.0' '46.0' '620.0' '703.0'
 '210.0' '1500.0' '232.0' '541.0' '270.0' '2.8' '77.0' '192.0' '763.0'
 '195.0' '110.0' '250.0' '56.9' '65500.0' '203.0' '63.0' '550.0' '243.0']
Uniques value in K
['4.4' '79.0' '90.0' '56.0' '78.0' '87.0' '77.0' '59.0' '61.0' '28.0'
 '75.0' '86.0' '54.0' '60.0' '53.0' '13.1' '55.0' '66.7' '49.0' '51.0'
 '40.0' '50.0' '22.6' '3.0' '249.0' '65.0' '70.0' '74.0' '2.3' '57.0'
 '4.7' '62.0' '41.0' '69.0' '5.8' '48.0' '64.0' '300.0' '0.2' '88.0' '4.3'
 '4.2' '38.0' '58.0' '5.0' '1.0' '154.0' '29.0' '8.8' '2.9' '72.0' '74.6'
 '76.8' '3800.0' '13.8' '31.2' '5000.0' '8.9' '1.4' '44.0' '67.6' '109.0'
 '21.0' '12.0' '6.1' '10.0' '3.2' '9.4' '39.0' '42.0' '30.0' '20.0' '0.6'
 '9.1' '8.7' '13.0' '22.0' '26.0' '6.0' '1250.0' '7.4' '32.0']
Uniques value in Ca
['86.0' '3.0' '3.4' '14.5' '8.2' '9.2' '1.4' '2.3' '2.7' '16.3' '13.8'
 '18.0' '2.6' '13.7' '15.8' '13.2' '14.4' '5.6' '14.9' '7.2' '13.9' '73.0'
 '98.0' '15.3' '16.0' '0.1' '28.1' '14.6' '23.0' '87.0' '14.8' '3.3' '3.2'
 '3.7' '20.6' '19.9' '0.8' '1.9' '42.4' '5.0' '2.5' '2.8' '4.8' '15.5'
 '5.4' '49.0' '5.5' '22.2' '19.0' '19.3' '11.0' '380.0' '0.2' '51.0' '2.0'
 '1.7' '14.0' '8.3' '245.0' '150.0' '110.0' '8.7' '8.4' '9.6' '9.0'
 '1700.0' '46.0' '10.0' '82.0' '44200.0' '17.0' '84.0' '7.4' '7.9' '273.0'
 '21.0' '78.0' '4.5' '14.7' '4.0' '70.0' '16.6' '7.7' '510.0' '58.0'
 '60.0' '53.0' '13.0' '6.7' '39.0' '1.0' '71.5' '32600.0' '29.0' '35.0'
 '56.0']
Uniques value in Mg
['31.0' '0.0' '0.1' '0.2' '< .07' '0.3' '5.3' '0.4' '< .01' '23.0' '21.0'
 '7.2' nan '< .02' '0.5' '10.2' '13.0' '0.6' '16.0' '1.0' '86.0' '14.0'
 '7.0' 'N' '42.0' '27.0' '2400.0' '< .002' '2.1' '3490.0' '0.7' '7.7'
 '32.0' '22.0' '15.0' '2.0' '1.7' '190.0' '1.6' '1.9' '4.4' '29.9'
 '3700.0' '0.8' '18.0']
Uniques value in Cl
['37.0' '50.0' '51.0' '54.0' '72.0' '73.0' '89.0' '105.0' '104.0' '102.0'
 '107.0' '61.0' '125.0' '124.0' '126.0' '120.0' '121.0' '135.0' '144.0'
 '139.0' '155.0' '171.0' '490.0' '56.0' '182.0' '193.0' '198.0' '600.0'
 '207.0' '13.0' '220.0' '15.0' '3740.0' '225.0' '779.0' '248.0' '250.0'
 '247.0' '246.0' '245.0' '261.0' '257.0' '17.2' '270.0' '267.0' '269.0'
 '268.0' '285.0' '288.0' '284.0' '40.0' '300.0' '299.0' '298.0' '308.0'
 '309.0' '332.0' '9100.0' '340.0' '365.0' '16.0' '395.0' '406.0' '407.0'
 '553.0' '421.0' '508.0' '2790.0' '1830.0' '160.0' '6.9' '642.0' '651.0'
 '652.0' '687.0' '110000.0' '705.0' '707.0' '1500.0' '210900.0' '212.0'
 '19.0' '702.0' '714.0' '8480.0' '83.0' '263.0' '32.0' '215.0' '718.0'
 '211.0' '760.0' '1.0' '870.0' '798.0' '49.0' '38.0' '2200.0' '869.0'
 '52.0' '0.9' '110.0' '123.0' '864.0' '955.0' '118.0' '12.0' '540.0'
 '900.0' '1019.0' '176600.0' '42.0' '1121.0' '172.0' '570.0' '1143.0'
 '1115.0']
Uniques value in SO4
['147.0' '81.0' '92.0' '125.0' '103.0' '89.0' '88.0' '100.0' '121.0'
 '126.0' '155.0' '102.0' '124.0' nan '122.0' '77.8' '197.0' '143.0'
 '120.0' '64.0' '47.6' '59.0' '70.0' '97.0' '104.0' '111.0' '129.0' '3.2'
 '115.0' '10.7' '112.0' '114.0' '127.0' '128.0' '18.0' '101.0' '116.0'
 '4.8' '94.0' '960.0' '1.5' '145.0' '4.5' '7.3' '140.0' '110.0' '130.0'
 '152.0' '45.0' '38.0' '293.0' '250.0' '73.0' '222.0' '213.0' '224.0'
 '6100.0' '658.0' '360.0' '160.0' '11.0' '19.0' '198.0' '37.0' '474.0'
 '209.0' '49.0' '12.0' '53.0' '123.0' '13.0' '180.0' '190.0' '90.0'
 '2200.0' '56.0' '580.0' '5.0' '187.0' '169.0' '55.0' '370.0' '57.0'
 '63.0' '87.7' '246.0' '348.0' '43.0' '52.0' '66.0' '457.0']

In [17]:
### Change str, e.g. '< 0.01' for numeric value (0.01)

# Define the columns to check
#columns_to_check = ['pH', 'K', 'Na', 'Ca', 'Mg', 'Cl', 'SO4']

columns_to_check = ['pH', 'K', 'Na', 'Ca', 'Mg', 'Cl', 'SO4']

check = '< .07'
value = 0.07

# Before replacement: Check for the presence of the str
print("Before replacement:")
for col in columns_to_check:
    # Count occurrences of the string
    count_before = df[df[col] == check].shape[0]
    print(f"Number of {check} values in {col}: {count_before}")
    # Show some example rows containing the value
    print(f"Example rows with {check} in {col}:")
    print(df[df[col] == check].head())

# Perform the replacement
for col in columns_to_check:
    df[col] = df[col].replace(check, value)
    #df[col] = pd.to_numeric(df[col], errors='coerce') # this function change all str to NaN, caution!!

# After replacement: Verify the changes
print("\nAfter replacement:")
for col in columns_to_check:
    # Count occurrences 
    count_after = df[df[col] == value].shape[0]
    print(f"\nNumber of {value} values in {col}: {count_after}")
    print(f"Unique values in {col}:")
    print((df[col].unique()))

Before replacement:
Number of < .07 values in pH: 0
Example rows with < .07 in pH:
Empty DataFrame
Columns: [well_sample, temp_measured, pH, Na, K, Ca, Mg, Cl, SO4]
Index: []
Number of < .07 values in K: 0
Example rows with < .07 in K:
Empty DataFrame
Columns: [well_sample, temp_measured, pH, Na, K, Ca, Mg, Cl, SO4]
Index: []
Number of < .07 values in Na: 0
Example rows with < .07 in Na:
Empty DataFrame
Columns: [well_sample, temp_measured, pH, Na, K, Ca, Mg, Cl, SO4]
Index: []
Number of < .07 values in Ca: 0
Example rows with < .07 in Ca:
Empty DataFrame
Columns: [well_sample, temp_measured, pH, Na, K, Ca, Mg, Cl, SO4]
Index: []
Number of < .07 values in Mg: 1
Example rows with < .07 in Mg:
             well_sample  temp_measured   pH     Na     K   Ca     Mg    Cl  \
289  Well 23-5-A-Recalc.          170.0  5.4  600.0  78.0  1.4  < .07  89.0

      SO4
289  89.0
Number of < .07 values in Cl: 0
Example rows with < .07 in Cl:
Empty DataFrame
Columns: [well_sample, temp_measured, pH, Na, K, Ca, Mg, Cl, SO4]
Index: []
Number of < .07 values in SO4: 0
Example rows with < .07 in SO4:
Empty DataFrame
Columns: [well_sample, temp_measured, pH, Na, K, Ca, Mg, Cl, SO4]
Index: []

After replacement:

Number of 0.07 values in pH: 0
Unique values in pH:
['10.0' '8.3' '6.2' '7.8' '5.4' '5.8' '5.7' '7.4' '6.4' '5.9' '6.3' '9.0'
 '7.2' nan '8.0' '6.1' '8.2' '6.0' '8.5' '7.1' '8.1' '4.8' '7.6' '8.4'
 '9.3' '8.9' '8.7' '9.2' '9.5' '9.6' '8.6' '9.9' '7.9' '6.6' '9.4' '7.3'
 '9.7' '4.5' '9.8' '7.7']

Number of 0.07 values in K: 0
Unique values in K:
['4.4' '79.0' '90.0' '56.0' '78.0' '87.0' '77.0' '59.0' '61.0' '28.0'
 '75.0' '86.0' '54.0' '60.0' '53.0' '13.1' '55.0' '66.7' '49.0' '51.0'
 '40.0' '50.0' '22.6' '3.0' '249.0' '65.0' '70.0' '74.0' '2.3' '57.0'
 '4.7' '62.0' '41.0' '69.0' '5.8' '48.0' '64.0' '300.0' '0.2' '88.0' '4.3'
 '4.2' '38.0' '58.0' '5.0' '1.0' '154.0' '29.0' '8.8' '2.9' '72.0' '74.6'
 '76.8' '3800.0' '13.8' '31.2' '5000.0' '8.9' '1.4' '44.0' '67.6' '109.0'
 '21.0' '12.0' '6.1' '10.0' '3.2' '9.4' '39.0' '42.0' '30.0' '20.0' '0.6'
 '9.1' '8.7' '13.0' '22.0' '26.0' '6.0' '1250.0' '7.4' '32.0']

Number of 0.07 values in Na: 0
Unique values in Na:
['53.2' '594.0' '673.0' '627.0' '593.0' '665.0' '600.0' '610.0' '691.0'
 '611.0' '624.0' '660.0' '604.0' '692.0' '636.0' '628.0' '613.0' '95.5'
 '644.0' '429.0' '615.0' '330.0' '52.0' '631.0' '633.0' '605.0' '980.0'
 '637.0' '135.0' '630.0' '19.0' '2230.0' '646.0' '560.0' '590.0' '639.0'
 '655.0' '608.0' '4.2' '15.0' '586.0' '569.0' '657.0' '614.0' '625.0'
 '686.0' '390.0' '547.0' '626.0' '623.0' '56.0' '640.0' '4700.0' '0.3'
 '840.0' '7.6' '8.4' '584.0' '690.0' '493.0' '596.0' '81.0' '1760.0'
 '1050.0' '62.0' '9.1' '497.0' '470.0' '506.0' '499.0' '63000.0' '332.0'
 '263.0' '1000.0' '74600.0' '185.0' '29.0' '55.0' '370.0' '450.0' '5470.0'
 '324.0' '298.0' '24.0' '193.0' '641.0' '180.0' '46.0' '620.0' '703.0'
 '210.0' '1500.0' '232.0' '541.0' '270.0' '2.8' '77.0' '192.0' '763.0'
 '195.0' '110.0' '250.0' '56.9' '65500.0' '203.0' '63.0' '550.0' '243.0']

Number of 0.07 values in Ca: 0
Unique values in Ca:
['86.0' '3.0' '3.4' '14.5' '8.2' '9.2' '1.4' '2.3' '2.7' '16.3' '13.8'
 '18.0' '2.6' '13.7' '15.8' '13.2' '14.4' '5.6' '14.9' '7.2' '13.9' '73.0'
 '98.0' '15.3' '16.0' '0.1' '28.1' '14.6' '23.0' '87.0' '14.8' '3.3' '3.2'
 '3.7' '20.6' '19.9' '0.8' '1.9' '42.4' '5.0' '2.5' '2.8' '4.8' '15.5'
 '5.4' '49.0' '5.5' '22.2' '19.0' '19.3' '11.0' '380.0' '0.2' '51.0' '2.0'
 '1.7' '14.0' '8.3' '245.0' '150.0' '110.0' '8.7' '8.4' '9.6' '9.0'
 '1700.0' '46.0' '10.0' '82.0' '44200.0' '17.0' '84.0' '7.4' '7.9' '273.0'
 '21.0' '78.0' '4.5' '14.7' '4.0' '70.0' '16.6' '7.7' '510.0' '58.0'
 '60.0' '53.0' '13.0' '6.7' '39.0' '1.0' '71.5' '32600.0' '29.0' '35.0'
 '56.0']

Number of 0.07 values in Mg: 1
Unique values in Mg:
['31.0' '0.0' '0.1' '0.2' 0.07 '0.3' '5.3' '0.4' 0.01 '23.0' '21.0' '7.2'
 nan 0.02 '0.5' '10.2' '13.0' '0.6' '16.0' '1.0' '86.0' '14.0' '7.0' 'nan'
 '42.0' '27.0' '2400.0' 0.002 '2.1' '3490.0' '0.7' '7.7' '32.0' '22.0'
 '15.0' '2.0' '1.7' '190.0' '1.6' '1.9' '4.4' '29.9' '3700.0' '0.8' '18.0']

Number of 0.07 values in Cl: 0
Unique values in Cl:
['37.0' '50.0' '51.0' '54.0' '72.0' '73.0' '89.0' '105.0' '104.0' '102.0'
 '107.0' '61.0' '125.0' '124.0' '126.0' '120.0' '121.0' '135.0' '144.0'
 '139.0' '155.0' '171.0' '490.0' '56.0' '182.0' '193.0' '198.0' '600.0'
 '207.0' '13.0' '220.0' '15.0' '3740.0' '225.0' '779.0' '248.0' '250.0'
 '247.0' '246.0' '245.0' '261.0' '257.0' '17.2' '270.0' '267.0' '269.0'
 '268.0' '285.0' '288.0' '284.0' '40.0' '300.0' '299.0' '298.0' '308.0'
 '309.0' '332.0' '9100.0' '340.0' '365.0' '16.0' '395.0' '406.0' '407.0'
 '553.0' '421.0' '508.0' '2790.0' '1830.0' '160.0' '6.9' '642.0' '651.0'
 '652.0' '687.0' '110000.0' '705.0' '707.0' '1500.0' '210900.0' '212.0'
 '19.0' '702.0' '714.0' '8480.0' '83.0' '263.0' '32.0' '215.0' '718.0'
 '211.0' '760.0' '1.0' '870.0' '798.0' '49.0' '38.0' '2200.0' '869.0'
 '52.0' '0.9' '110.0' '123.0' '864.0' '955.0' '118.0' '12.0' '540.0'
 '900.0' '1019.0' '176600.0' '42.0' '1121.0' '172.0' '570.0' '1143.0'
 '1115.0']

Number of 0.07 values in SO4: 0
Unique values in SO4:
['147.0' '81.0' '92.0' '125.0' '103.0' '89.0' '88.0' '100.0' '121.0'
 '126.0' '155.0' '102.0' '124.0' nan '122.0' '77.8' '197.0' '143.0'
 '120.0' '64.0' '47.6' '59.0' '70.0' '97.0' '104.0' '111.0' '129.0' '3.2'
 '115.0' '10.7' '112.0' '114.0' '127.0' '128.0' '18.0' '101.0' '116.0'
 '4.8' '94.0' '960.0' '1.5' '145.0' '4.5' '7.3' '140.0' '110.0' '130.0'
 '152.0' '45.0' '38.0' '293.0' '250.0' '73.0' '222.0' '213.0' '224.0'
 '6100.0' '658.0' '360.0' '160.0' '11.0' '19.0' '198.0' '37.0' '474.0'
 '209.0' '49.0' '12.0' '53.0' '123.0' '13.0' '180.0' '190.0' '90.0'
 '2200.0' '56.0' '580.0' '5.0' '187.0' '169.0' '55.0' '370.0' '57.0'
 '63.0' '87.7' '246.0' '348.0' '43.0' '52.0' '66.0' '457.0']

NWIS Well 003S028E32E006M                              19
NWIS Well 003S028E32E005M                              12
California State 2-14 well                             11
NDOT Well                                               6

In [14]:
### Filter specific well to keep only row with index 238
well_name = "Y.C. well 23-5"

idx_to_keep = [380]


# Create mask to keep specified rows for the well
mask = ((df['well_sample'] == well_name) & (df.index.isin(idx_to_keep))) | (df['well_sample'] != well_name)

# Apply the filter
df = df[mask]

print(f"\nVerifying filtered results for {well_name}:")
display(df[df['well_sample'] == well_name])

print("\nTotal rows in dataset after filtering:", len(df))

Verifying filtered results for Y.C. well 23-5:

        well_sample  temp_measured   pH     Na     K   Ca   Mg     Cl    SO4
380  Y.C. well 23-5          167.8  7.9  692.0  86.3  2.7  0.1  119.0  129.0

Total rows in dataset after filtering: 115

In [15]:
# Define indices to remove
indices_to_remove = [654,707,720,724,401,416,418,471,476,504,515,514,661,
                     670,379,383,550,575,591,623,522,524,506,197,198,206,210,150]

# Remove rows with specified indices
df = df[~df.index.isin(indices_to_remove)]

print("\nVerifying removal of specified indices:")
print(f"Indices {indices_to_remove} present in dataset: ", 
      any(idx in df.index for idx in indices_to_remove))

print("\nTotal rows in dataset after filtering:", len(df))

Verifying removal of specified indices:
Indices [654, 707, 720, 724, 401, 416, 418, 471, 476, 504, 515, 514, 661, 670, 379, 383, 550, 575, 591, 623, 522, 524, 506, 197, 198, 206, 210, 150] present in dataset:  False

Total rows in dataset after filtering: 87

In [18]:
print(df)

df = df.reset_index(drop=True)
print("Index has been reset")
print(df)

                       well_sample  temp_measured    pH     Na     K    Ca  \
180     Utah State 42-7 Well                178.0  10.0   53.2   4.4  86.0
208            Well 23-5-C-Recalc.          172.8   8.3  594.0  79.0   3.0
209                    Well 23-5-C          172.8   8.3  673.0  90.0   3.4
215                    PW-3-A well          172.2   6.2  627.0  56.0  14.5
241            Well 23-5-E-Recalc.          171.1   7.8  593.0  78.0   8.2
...                            ...            ...   ...    ...   ...   ...
3085                   Osborn Well           90.0   9.5   63.0  10.0  82.0
3089                  UNNAMED WELL           90.0   5.9  370.0  32.0  35.0
3095  NWIS Well  (A-13- 1)19cac- 1           90.0   NaN  550.0  40.0  56.0
3120   MOANA AREA - OLD YATES WELL           90.0   8.3  243.0   7.4  23.0
3121                OLD YATES WELL           90.0   8.3  243.0   7.4  23.0

        Mg      Cl    SO4
180   31.0    37.0  147.0
208    0.0    50.0   81.0
209    0.1    51.0   92.0
215    0.2    54.0  125.0
241    0.0    72.0   92.0
...    ...     ...    ...
3085  18.0   172.0   43.0
3089   0.1   570.0   52.0
3095   0.2  1143.0   66.0
3120   0.2    50.0  457.0
3121   0.2  1115.0  457.0

[126 rows x 9 columns]
Index has been reset
                      well_sample  temp_measured    pH     Na     K    Ca  \
0      Utah State 42-7 Well                178.0  10.0   53.2   4.4  86.0
1             Well 23-5-C-Recalc.          172.8   8.3  594.0  79.0   3.0
2                     Well 23-5-C          172.8   8.3  673.0  90.0   3.4
3                     PW-3-A well          172.2   6.2  627.0  56.0  14.5
4             Well 23-5-E-Recalc.          171.1   7.8  593.0  78.0   8.2
..                            ...            ...   ...    ...   ...   ...
121                   Osborn Well           90.0   9.5   63.0  10.0  82.0
122                  UNNAMED WELL           90.0   5.9  370.0  32.0  35.0
123  NWIS Well  (A-13- 1)19cac- 1           90.0   NaN  550.0  40.0  56.0
124   MOANA AREA - OLD YATES WELL           90.0   8.3  243.0   7.4  23.0
125                OLD YATES WELL           90.0   8.3  243.0   7.4  23.0

       Mg      Cl    SO4
0    31.0    37.0  147.0
1     0.0    50.0   81.0
2     0.1    51.0   92.0
3     0.2    54.0  125.0
4     0.0    72.0   92.0
..    ...     ...    ...
121  18.0   172.0   43.0
122   0.1   570.0   52.0
123   0.2  1143.0   66.0
124   0.2    50.0  457.0
125   0.2  1115.0  457.0

[126 rows x 9 columns]

In [ ]:
### Check complete name for index 720
if 720 in df.index:
    print("Complete name for index 720:")
    print(f"{'='*50}")
    print(df.loc[720, 'Name'])
    print(f"{'='*50}")
    # Display full row information
    print("\nFull row information:")
    display(df.loc[[720]])
else:
    print("Index 720 not found in the DataFrame")

if 720 in df.index:
    df.loc[720, 'Name'] = 'USGS Drill Hole Well GS-1'
    print("Name changed successfully")
    print("\nVerifying change:")
    display(df.loc[[720]])
else:
    print("Index 720 not found in the DataFrame")

In [19]:
### Check for non-numeric 

columns_to_check = ['pH', 'K', 'Na', 'Ca', 'Mg', 'Cl', 'SO4']

print("Checking for non-numeric values:")
for col in columns_to_check:
    # Check if column is numeric
    is_numeric = pd.to_numeric(df[col], errors='coerce')
    
    # Find non-numeric values (will be NaN after coercion)
    non_numeric_mask = is_numeric.isna() & ~df[col].isna()
    non_numeric_values = df[non_numeric_mask][col]
    
    if len(non_numeric_values) > 0:
        print(f"\nColumn {col} has {len(non_numeric_values)} non-numeric values:")
        print("Sample of non-numeric values:")
        print(non_numeric_values.head())
        print("Unique non-numeric values:", df[non_numeric_mask][col].unique())
    else:
        print(f"\nColumn {col}: All values are numeric")
        print(f"Data type: {df[col].dtype}")

Checking for non-numeric values:

Column pH: All values are numeric
Data type: object

Column K: All values are numeric
Data type: object

Column Na: All values are numeric
Data type: object

Column Ca: All values are numeric
Data type: object

Column Mg has 1 non-numeric values:
Sample of non-numeric values:
70    nan
Name: Mg, dtype: object
Unique non-numeric values: ['nan']

Column Cl: All values are numeric
Data type: object

Column SO4: All values are numeric
Data type: object

In [20]:
### Save the cleaned DataFrame too csv file
output_path = 'csv/dataset_GDR_cleaned_90-180.csv'

# Create the directory if it doesn't exist
import os
os.makedirs('csv', exist_ok=True)

# Save to CSV without the index column
df.to_csv(output_path, index=False)

print(f"Data successfully saved to: {output_path}")
print(f"Number of rows saved: {len(df)}")

Data successfully saved to: csv/dataset_GDR_cleaned_90-180.csv
Number of rows saved: 126

In [21]:
### Load and combine datasets

df1 = pd.read_csv('csv/final_dataset.csv')

df2 = pd.read_csv('csv/dataset_GDR_cleaned_90-180.csv')  

# Combine datasets vertically
combined_df = pd.concat([df1, df2], axis=0, ignore_index=True)

# Save the combined dataset
output_path = 'csv/combined_dataset_90-120.csv'
combined_df.to_csv(output_path, index=False)

print(f"Original datasets shapes:")
print(f"Dataset 1: {df1.shape}")
print(f"Dataset 2: {df2.shape}")
print(f"\nCombined dataset shape: {combined_df.shape}")
print(f"Data successfully saved to: {output_path}")

Original datasets shapes:
Dataset 1: (216, 9)
Dataset 2: (126, 9)

Combined dataset shape: (342, 9)
Data successfully saved to: csv/combined_dataset_90-120.csv